language: "en"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
  name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"

policies:
- name: "KerasPolicy"
  epochs: 100
  max_history: 5
- name: "MemoizationPolicy"
  max_history: 5
- name: "MappingPolicy"
- name: "FallbackPolicy"
  nlu_threshold: 0.4
  core_threshold: 0.3
  fallback_action_name: "action_default_fallback"